### PR TITLE
Midisrv abstraction and cross process client

### PR DESCRIPTION
**Pull request by garydan42**
MidiSrvAbstraction uses RPC calls on MidiSrv to create a MIDI client on the service. This allocates shared position "registers," allocates a double mapped cross process memory mapped buffer (using a trick of virtual memory, up to 1 buffer size worth of data written past the "end" of the primary buffer wraps around to the beginning of the buffer), and creates a shared event to signal when data is ready.

MidiSrv only supports instantiating a single IMidiBiDi pipe with the client layer and connecting it to a single IMidiBiDi pipe using KSAbstraction. Multi-client support to come later.

MidiXProc is a new library which contains the client to server buffer allocation code and a shared implementation for moving data across the mapped memory, used by KSAbstraction and MidiSrv for client to server, and by MidiSrvAbstraction for server to kernel mode.

Midi2.Abstraction.Unittests now instantiates a MidiSrvAbstraction, which creates a MidiSrv client with cross process memory mapped buffers from the test to the service. The service instantiates a KSAbstraction, which instantiates KS pins on MinMidi and cross process memory mapped buffers from the service to kernel mode. MinMidi then copies the data from the midi out buffer to the midi in buffer and sets the event, looping the data from midi out to midi in. With this we can now test functionality and performance of midi data flowing from Midi2.Abstraction.Unittests, through the service, to the driver, and back.

Performance shows that latency is slightly higher (couple milliseconds) when the test uses MidiSrvAbstraction vs KSAbstraction, which is expected. Throughput is the same whether going through the service or not.

### CODE REVIEW

**Review by Psychlist1972 — APPROVED** [review]

**Comment by bome** [comment]
forgive me if I miss the context, but this caught my eye (or ear...):

> latency is slightly higher (couple milliseconds) when the test uses MidiSrvAbstraction vs KSAbstraction

That seems like a lot of additional latency! I would hope that software components merely use a couple of _microseconds_ for MIDI...

**Comment by garydan42** [comment]
Hi Florian,

The PR comment was made based upon some preliminary data collection that was done using debug builds of all components and was primarily just a sanity test around functionality of the system. Here's some of the current performance data. These tests are all part of the repo, part of the driver unit tests and abstraction unit tests. So, everything is there for anyone to build and run them.

I'll caveat this first by saying this is all in-development and beyond the initial design plan focusing on improving performance, no additional performance work or optimizations have been performed yet.

All data is gathered using the fully software "MinMidi" KS driver which simply copies the data from midi out back to midi in with no internal processing performed or hardware latencies. This driver supports both the legacy midi implementation where messages are sent and received via a device IOCtl call, and the new cyclic implementation using memory mapped buffers with an event.

This test measures by sending 100,000 separate midi messages, one at a time, as fast as possible. Each message is given the current QPC as its timestamp, and each message contains a UMP 128 bit payload. I have other tests which send different sized messages, and send messages at a slower rate, but this test represents the worst case data.

Round trip latency data is the time from the when the message was generated and put into the midi out data buffer to the point where that same message was received back as a midi in message.

Message send jitter measures performance of putting a midi message into the midi out buffer.

Midi receive jitter measures the time between receiving midi messages.

Let me know if you have any additional questions or suggestions.

Thanks,
-Gary

---------------------------------------
Performance data for the legacy windows midi solution

Messages per second 135,573.918

RoundTrip latencies
Average round trip latency 2.6083 ms
First message round trip latency 0.1675 ms
Last message round trip latency 6.3523 ms
Smallest round trip latency 0.0065 ms
Largest round trip latency 11.113 ms

Message send jitter
Average message send 0.0299 ms
First message send 0.197 ms
Last message send 0.0061 ms
Smallest message send 0.0049 ms
Largest message send 0.271 ms

Message receive jitter
Average message receive 0.03 ms
Largest message receive 0.2165 ms
Smallest message receive 0.0046 ms
---------------------------------------
Performance data for direct use of memory mapped cyclic buffers

Messages per second 1,744,762.22

RoundTrip latencies
Average round trip latency 0.0245 ms
First message round trip latency 0.0385 ms
Last message round trip latency 0.0007 ms
Smallest round trip latency 0.0002 ms
Largest round trip latency 0.1337 ms

Message send jitter
Average message send 0.0016 ms
First message send 0.0144 ms
Last message send 0.0002 ms
Smallest message send 0.0002 ms
Largest message send 0.0757 ms

Message receive jitter
Average message receive 0.0008 ms
Largest message receive 0.1528 ms
Smallest message receive 0 ms

---------------------------------------
Performance data for memory mapped cyclic buffers flowing through midisrv
There is a memory mapped cyclic buffer from user mode to the service, and a second from the service to the driver
The service is not performing any additional processing beyond copying the data

Messages per second 1,658,671.87

RoundTrip latencies
Average round trip latency 0.2727 ms
First message round trip latency 0.1707 ms
Last message round trip latency 0.5729 ms
Smallest round trip latency 0.01 ms
Largest round trip latency 2.3395 ms

Message send jitter
Average message send 0.0025 ms
First message send 0.0322 ms
Last message send 0.0002 ms
Smallest message send 0.0002 ms
Largest message send 0.1257 ms

Message receive jitter
Average message receive 0.0004 ms
Largest message receive 0.141 ms
Smallest message receive 0 ms


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Psychlist1972** [comment]
Thanks Gary! Florian, I'll be interested in your feedback on the above. Do note that the numbers are in milliseconds, not seconds and this is the scenario as Gary described. If users opt for additional processing of messages (MIDI mapper-type stuff) those will obviously increase latency. There's also the read/write process from the app itself which will add a little bit.

**Comment by bome** [comment]
Thanks Gary, too! These detailed numbers are probably OK, considering that you're using a non-optimized debug build. Only the roundtrip latency of the "legacy windows midi solution" seems problematic, but optimization could fix that, too.

Just as comparison, my own "legacy" virtual MIDI driver's roundtrip latency is in the ballpark of 14 microseconds for sending from the virtual port and 40 microseconds for receiving on the virtual port with typically less than a microsecond jitter. Using an own benchmark which just sends individual messages and measures the duration between sending and receiving.

**Comment by Psychlist1972** [comment]
> Thanks Gary, too! These detailed numbers are probably OK, considering that you're using a non-optimized debug build. Only the roundtrip latency of the "legacy windows midi solution" seems problematic, but optimization could fix that, too. And it's great that you're running these benchmarks!
> 
> Just as comparison, my own "legacy" virtual MIDI driver's roundtrip latency is in the ballpark of 14 microseconds for sending from the virtual port and 40 microseconds for receiving on the virtual port with typically less than a microsecond jitter. Using an own benchmark which just sends individual messages and measures the duration between sending and receiving.

Florian, is that a Windows MIDI Driver, or code in your Bome box? Can you tell me a bit more about the testing?

Whenever I've tested USB MIDI 1.0 devices, the round trip is significantly slower, and it's not an area I have any real knowledge in (that's for Gary, Egidio and others), but I wasn't aware of anything we had available for drivers which would service the calls fast enough to get within a microsecond jitter.

Pete

**Comment by bome** [comment]
It's a pure software driver providing virtual MIDI ports on Windows. By way of the "Bome Virtual MIDI" API ("BMIDI"), you can add/remove virtual MIDI ports and send/receive MIDI data to/from it. These virtual MIDI ports are available to other applications as MME and DirectMusic devices.

Now the first test sends a MIDI message using BMIDI and measures the time until it arrives on the public MME INPUT port. I've just re-run the test on my office PC and latency is consistently either 14 or 15 microseconds.

The second test sends a message to a virtual MME OUTPUT port and waits until it appears on the respective BMIDI port. The latency here is consistently 39 or 40 microseconds, with two outliers of 37 and 41.

The tests are run in one process (which makes measuring time intervals easy), but the MIDI message will pass through the kernel driver stack in both tests.

Disclaimer: I think that this (old) benchmark program is correctly implemented, but no guarantees... I've been developing this driver since the mid-2000's.

> Whenever I've tested USB MIDI 1.0 devices, the round trip is significantly slower
Yes, definitely. USB polled in 1 millisecond intervals will have that much jitter.

**Comment by Psychlist1972** [comment]
Thanks Florian. I'm not a driver guy (as I keep saying, just so others know), but I didn't know the kernel streaming driver threads were even serviced at that interval, but good to know.

**Comment by Psychlist1972** [comment]
> It's a pure software driver providing virtual MIDI ports on Windows. By way of the "Bome Virtual MIDI" API ("BMIDI"), you can add/remove virtual MIDI ports and send/receive MIDI data to/from it. These virtual MIDI ports are available to other applications as MME and DirectMusic devices.
> 
> Now the first test sends a MIDI message using BMIDI and measures the time until it arrives on the public MME INPUT port. I've just re-run the test on my office PC and latency is consistently either 14 or 15 microseconds.
> 
> The second test sends a message to a virtual MME OUTPUT port and waits until it appears on the respective BMIDI port. The latency here is consistently 39 or 40 microseconds, with two outliers of 37 and 41.
> 
> The tests are run in one process (which makes measuring time intervals easy), but the MIDI message will pass through the kernel driver stack in both tests.
> 
> Disclaimer: I think that this (old) benchmark program is correctly implemented, but no guarantees... I've been developing this driver since the mid-2000's.
> 
> > Whenever I've tested USB MIDI 1.0 devices, the round trip is significantly slower
> > Yes, definitely. USB polled in 1 millisecond intervals will have that much jitter.

As a follow-up to this, thought I'd post some preliminary round-trip benchmarks for the API. There's always risk in this, but I think the numbers here are reasonable to share at this point.

This is a cross-process test, but is entirely user-mode, because endpoints like virtual, BLE, network, etc. are all user-mode plugins. Brackets are process boundaries. This is all on Windows 11 x64. Service is compiled to release mode, and installed on Windows. API and test project are running in Visual Studio. 

_Test Project -> API  ->[ MidiSrv -> Hard-coded loopback out to in -> Callback ] -> API -> Test Project_

* Test Project: Catch2 test project running in Visual Studio 2022, using the WinRT API
* API: WinRT API Project running in Visual Studio 2022
* MidiSrv: Windows Service for Windows MIDI Services. Communication to/from API is via shared memory buffer

I'm using a customized version of the service with a simple loopback in it implemented as a single bidirectional endpoint. Anything sent up, is sent right back down as-is, including the 64 bit timestamp.

```cpp
_Use_decl_annotations_
HRESULT
CMidi2SampleMidiBiDi::SendMidiMessage(
    PVOID message,
    UINT size,
    LONGLONG position
)
{
    // just echo the message back to the callback

    if (_callback != nullptr && message != nullptr && size >= sizeof(uint32_t))
    {
        _callback->Callback(message, size, position);

        return S_OK;
    }
    else
    {
        OutputDebugString(L"CMidi2SampleMidiBiDi::SendMidiMessage Something is null");
    }

    return E_FAIL;

}
```

In the test, I send a mix of messages up and get them back in the callback. There's an unsophisticated loop that waits for all messages to be received, consisting of a countdown and Sleep(0) statements.

```cpp
uint32_t timeoutCounter = 1000000;
uint32_t numSleepCalls = 0;
uint32_t sleepDuration = 0;

while (receivedMessageCount < numMessagesToSend && timeoutCounter > 0)
{
	Sleep(sleepDuration);

	timeoutCounter--;
	numSleepCalls++;
}
```

The WinRT callback just counts up the messages and tracks the timestamp difference

```cpp
auto MessageReceivedHandler = [&receivedMessageCount, &timestampDeltas](Windows::Foundation::IInspectable const& sender, MidiMessageReceivedEventArgs const& args)
	{
		REQUIRE((bool)(args != nullptr));

		receivedMessageCount++;

		// this is to help with calculating jitter. Keep in mind that jitter will be 
		// negatively affected by our receive loop as well, but should be close enough
		// to real-world expectations
		uint64_t currentStamp = MidiClock::GetMidiTimestamp();
		uint64_t umpStamp = args.Ump().Timestamp();
		timestampDeltas.push_back(currentStamp - umpStamp);
	};

auto eventRevokeToken = conn1.MessageReceived(MessageReceivedHandler);
```

Caveats about development benchmarks apply. These aren't official, nor are they a promise/commitment, kernel mode transitions will have a cost, USB will have a cost, etc. This is on my primary PC which is an i9-9900k at standard clock speed running latest Windows 11 Pro.

```
Num Messages:                1000
- Count UMP32                336
- Count UMP64                332
- Count UMP96                83
- Count UMP128               249
Num Bytes (inc timestamp):   16980
Timestamp Frequency:         10000000 hz (ticks/second)
-----------------------------
Setup Start Timestamp:       1569862247597
Setup/Connection Delta:      63169 ticks
Sending Start timestamp:     1569862310766
Sending Stop timestamp:      1569862365677
Send/Rec End timestamp:      1569862430532
Sending/Receiving Delta:     119766 ticks
Num Wait loop Sleep Calls:   12977

Prep
- Setup and connect:           6.316900ms (0.006317 seconds, 6316.900000 microseconds).

Send loop
- Send only:                   5.491100ms (0.005491 seconds, 5491.100000 microseconds).
- Average single send          0.005491ms (5.491100 microseconds).

Send Loop, Receive Loop, Callback
- Send/receive total:          11.976600ms (0.011977 seconds, 11976.600000 microseconds).

Single message round-trip
- Average single send/receive: 0.011977ms (11.976600 microseconds).
- Min single send/receive:     0.000063ms (0.062500 microseconds).
- Max single send/receive:     0.006487ms (6.486700 microseconds).

Round-trip jitter
- Max - min:                   0.006424ms (6.424200 microseconds).
- Average:                     0.003605ms (3.605130 microseconds).
- Standard deviation:          0.001687ms (1.687421 microseconds).
```

**Pull request merged**
